remote_theme: pmarsceill/just-the-docs

favicon_ico: "/images/favicon.png"
color_scheme: dark

title: "rpm hub"

aux_links:
  "Lattes":
    - "http://lattes.cnpq.br/9833435909646555"
  "ORCID":
    - "http://orcid.org/0000-0003-0428-6387"
  "Github":
    - "https://github.com/rodrigoprestesmachado"

# Google Analytics
ga_tracking:  G-R5MTNW4LKS
ga_tracking_anonymize_ip: true

# Footer content appears at the bottom of every page's main content
footer_content: "Copyright &copy; 2024 <a href='https://rpmhub.dev'>RPM Hub</a>."
